server.port=${PORT}
spring.data.mongodb.uri=mongodb+srv://${USERNAME}:${PASSWORD}@${CLUSTER_NAME}.dnjfndz.mongodb.net/?retryWrites=true&w=majority&appName=${CLUSTER_NAME}/${DATABASE_NAME}
logging.level.web=DEBUG